model:
  in_node_nf: 9     # [Pos(3), MixedVel(3), Type(2), Stress(1)]
  hidden_nf: 128
  out_node_nf: 4    # [Vel(3), Stress(1)]
  n_layers: 4
  attention: true

data:
  data_dir: "../pytorch_model/raw_data"
  preprocessed_dir: "egnn_preprocessed"
  split: "train"
  max_trajs: null   # Set to 10 for debugging, null for full run
  
  # Physics Parameters
  radius: 0.03      # Collision search radius

training:
  lr: 0.0001
  epochs: 500
  batch_size: 16    # Keep small for graph methods
  device: "cuda"
  seed: 42