model:
  in_node_nf: 9
  hidden_nf: 128
  out_node_nf: 4
  n_layers: 4
  attention: true

data:
  data_dir: "../pytorch_model/raw_data"
  preprocessed_dir: "egnn_preprocessed"
  split: "train"
  max_trajs: null
  radius: 0.03

training:
  lr: 0.0001
  epochs: 500
  batch_size: 16
  device: "cuda"
  seed: 42
  
  # --- RESTORED OVERFIT CONFIG ---
  mode: "standard"          # "standard" or "overfit"
  overfit_traj_ids: [0]     # Which trajectory to memorize
  overfit_time_ids: [0,1,2] # Which time steps to memorize