import os
import torch
from typing import List, Optional, Tuple
from torch.utils.data import Dataset
from torch_geometric.data import Data

# Feature layout for EGNN
# [Pos(3), Vel(3), Type(2), Stress(1)] = 9
FEATURE_DIM = 9  
TARGET_DIM = 4   # [Vel(3), Stress(1)]

STATS_FILE = "egnn_stats.pt"
INDEX_FILE = "egnn_index.pt"
TRAJ_TEMPLATE = "egnn_traj_{:05d}.pt"
PREPROCESSED_DIR = "egnn_preprocessed"

def _normalize_id_list(ids):
    if ids is None: return None
    if isinstance(ids, int): return [int(ids)]
    if isinstance(ids, str) and "-" in ids:
        start, end = map(int, ids.split("-"))
        return list(range(start, end + 1))
    if isinstance(ids, (list, tuple)):
        flat = []
        for v in ids:
            if isinstance(v, (list, tuple)): flat.extend([int(x) for x in v])
            else: flat.append(int(v))
        return flat
    return [int(ids)]

class EGNNTFRecordDataset(Dataset):
    """
    Optimized dataset for EGNN with RAM Caching.
    Loads preprocessed .pt files generated by egnn_preprocess.py.
    """

    def __init__(
        self,
        data_dir: str,
        split: str = "train",
        preprocessed_dir: Optional[str] = None,
        allowed_traj_ids: Optional[List[int]] = None,
        allowed_time_ids: Optional[List[int]] = None,
        transform=None,
        cache_all_in_ram: bool = True,
    ):
        super().__init__()
        self.data_dir = data_dir
        self.pre_dir = preprocessed_dir or os.path.join(data_dir, PREPROCESSED_DIR)
        self.transform = transform
        self.cache_all = cache_all_in_ram

        # 1. Load Stats & Index
        stats_path = os.path.join(self.pre_dir, STATS_FILE)
        index_path = os.path.join(self.pre_dir, INDEX_FILE)
        
        if not os.path.exists(stats_path):
            raise FileNotFoundError(f"Stats not found at {stats_path}. Run egnn_preprocess.py first.")

        stats = torch.load(stats_path, map_location="cpu", weights_only=False)
        self.mean_feat = stats["mean_feat"].float()
        self.std_feat = stats["std_feat"].float()
        self.mean_target = stats["mean_target"].float()
        self.std_target = stats["std_target"].float()
        
        self.feature_dim = FEATURE_DIM
        self.target_dim = TARGET_DIM

        index_data = torch.load(index_path, map_location="cpu", weights_only=False)
        full_index_list = index_data["index"]

        # 2. Filtering Logic (Trajectory & Time)
        allowed_traj_ids = _normalize_id_list(allowed_traj_ids)
        allowed_time_ids = _normalize_id_list(allowed_time_ids)
        
        allowed_traj_set = set(allowed_traj_ids) if allowed_traj_ids else None
        allowed_time_set = set(allowed_time_ids) if allowed_time_ids else None

        self.index_list = []
        for (tr, t) in full_index_list:
            if allowed_traj_set is not None and tr not in allowed_traj_set:
                continue
            if allowed_time_set is not None and t not in allowed_time_set:
                continue
            self.index_list.append((tr, t))

        self.available_traj = sorted(list(set(idx for idx, _ in self.index_list)))
        
        # 3. RAM Cache Setup
        self._traj_cache = {} 
        
        if self.cache_all:
            for tr_id in self.available_traj:
                self._load_traj_to_cache(tr_id)

    def __len__(self) -> int:
        return len(self.index_list)

    def _load_traj_to_cache(self, traj_idx: int):
        if traj_idx in self._traj_cache:
            return self._traj_cache[traj_idx]
            
        traj_path = os.path.join(self.pre_dir, TRAJ_TEMPLATE.format(traj_idx))
        if not os.path.exists(traj_path):
            raise FileNotFoundError(f"Trajectory file missing: {traj_path}")
            
        data = torch.load(traj_path, map_location="cpu", weights_only=False)
        self._traj_cache[traj_idx] = data
        return data

    def __getitem__(self, idx: int) -> Data:
            traj_idx, time_idx = self.index_list[idx]
            traj = self._load_traj_to_cache(traj_idx)
            
            # 1. Load Raw Tensors
            x = traj["x"][time_idx].float()       # [N, 9]
            y = traj["y"][time_idx].float()       # [N, 4]
            node_type = traj["node_type"].long()  # [N]
            edge_index = traj["edge_index"].long()
            
            # 2. Apply Normalization (CRITICAL FIX)
            # Stats are on CPU, moving to tensor device if needed
            mean_feat = self.mean_feat.to(x.device)
            std_feat = self.std_feat.to(x.device)
            mean_target = self.mean_target.to(y.device)
            std_target = self.std_target.to(y.device)
            
            # Normalize Input: (x - mean) / std
            x = (x - mean_feat) / std_feat
            
            # Normalize Target: (y - mean) / std
            y = (y - mean_target) / std_target
            
            data = Data(x=x, y=y, edge_index=edge_index, node_type=node_type)

            if self.transform is not None:
                data = self.transform(data)
                
            return data